name: devops_agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.0
  - pip:
    - python-dotenv==1.0.0
    - pyTelegramBotAPI==4.14.0
    - openai==1.65.2
    - anthropic==0.49.0